site_name: FusionSuite documentation
site_url: https://fusionsuite.org/documentation

repo_name: fusionSuite/documentation
repo_url: 'https://github.com/fusionSuite/documentation'

copyright: Copyright © FusionSuite 2022

nav:
  - Home: index.md
  - End-user guide: 
    - End-user guide/introduction.md
  - Administrator: 
    - administrators/index.md
    - administrators/cli_usage.md
    - administrators/requirements.md
    - Installation:
      - administrators/installation/backend.md
      - administrators/installation/frontend.md
  - Developers: 
    - developers/index.md
    - installation: developers/installation.md
    - tests: developers/tests.md

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 5
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://fusionsuite.org/
      name: Website
    - icon: fontawesome/brands/github
      link: https://github.com/fusionSuite
      name: FusionSuite on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FusionSuite
      name: FusionSuite on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Kj72FwAKTC
      name: FusionSuite on Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UClK5zin1sdONo2_P2fVuFKg
      name: FusionSuite on Youtube

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.annotate # (1)
    - content.code.copy
    - content.action.edit
  logo: assets/favicon.png
  favicon: assets/favicon.png

extra_css:
  - stylesheets/extra.css
